language: python

python:
  - 2.7

before_install:
  - git submodule update --init --recursive

install:
  # Install build dependencies
  - sudo apt-get update
  - sudo apt-get install libcurl4-openssl-dev

script:
  # Try to install the package
  - pip install .

  # See if the module got installed properly
  - python -c 'import xcsoar'

notifications:
  email:
    on_failure: change

deploy:
  provider: pypi
  user: Tobias.Bieniek
  password:
    secure: a7VeLjfa5BqojsRNa+RLu8YaagM1FFEzfuovLYnUxd0EC+6060VZyXBp06wINpqntDYPl4qfdNjZcAWsoSh02apjWYCw9LiRkRB5FlygulTFyUbc/qW5Ol/NzkQP2jpMW82eehE7wroj9Dfwp0zU4WDgUugPmDQxtpHRSR+34mA=
  on:
    tags: true
    repo: Turbo87/py-xcsoar
